"""add items.created_at

Revision ID: 0a5f4960c11b
Revises: 637d628b7e2b
Create Date: 2026-08-25 21:13:46.993366

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0a5f4960c11b"
down_revision: str | Sequence[str] | None = "637d628b7e2b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default now() also backfills rows that already exist, which is what
    # keeps the column NOT NULL on a non-empty table.
    op.add_column(
        "items",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("items", "created_at")
    # ### end Alembic commands ###
