"""create items table

Revision ID: 637d628b7e2b
Revises:
Create Date: 2026-08-25 17:06:04.546909

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "637d628b7e2b"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    items = op.create_table(
        "items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("value", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###

    # Seed the sample items the template used to hardcode. Ids are left to the
    # identity sequence so it stays in step; on a fresh table they come out 1-3.
    op.bulk_insert(
        items,
        [
            {"name": "Service Item 1", "value": 100},
            {"name": "Service Item 2", "value": 200},
            {"name": "Service Item 3", "value": 300},
        ],
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("items")
    # ### end Alembic commands ###
